### ISSUE TITLE
Fails when run with too long a period

### ISSUE THREAD

**Issue by chrissamuel** [sterni1971/wasteReport#1]
Using the example from the mailing list the code fails with a Python error:

```
# python ./wasteReport.py --partition --start "11/01-00:00" --order Efficiency
Traceback (most recent call last):
  File "./wasteReport.py", line 123, in <module>
    jobs.add(jobLine)
  File "./wasteReport.py", line 48, in add
    self.job=Job(jobdata)
  File "./wasteReport.py", line 37, in __init__
    self.totalcpu=mkSecond(self.totalcpu)
  File "./wasteReport.py", line 24, in mkSecond
    hour=int(shortTimeList[0])
ValueError: invalid literal for int() with base 10: ''
```

When run on a shorter interval it appears to succeed.

```
# python ./wasteReport.py --partition --start "11/10-00:00" --order Efficiency
partition:main,Efficiency:82.7%,LostSeconds:98799953
```

This is with Python 2.7.5 and 2.7.13.

**Comment by sterni1971** [comment]
It looks like sacct report for a job in your DB an empty field for TotalCPU.
I catch now the exception and set the TotalCPU for this job to 0.

**Comment by chrissamuel** [comment]
Thanks!   Looks good...

```
# python ./wasteReport.py --partition --start "11/01-00:00" --order Efficiency
WARN: Job 6967119: Couldn't convert TotalCPU time string into seconds:
partition:main,Efficiency:79.3%,LostSeconds:238986931
```

Now I can check out what's the deal for that job. ;-)
